# Generated by Django 5.0.7 on 2024-08-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_delete_payments"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ManyToManyField(
                to="materials.course", verbose_name="Оплаченный курс"
            ),
        ),
    ]
